# 2.3.3 Indexing Data

Sometimes we want to examine only a part of a set of data.

In [1]:
(A <- matrix(1:16, 4, 4))

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [2]:
A[2,3]

[1] 10

In [3]:
A[c(1,3), c(2,4)]

[,1] [,2]
[1,] 5    13  
[2,] 7    15

In [4]:
A[,1:2]

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

In [5]:
dim(A)

[1] 4 4