# 2.3.1 Basic Commands

To create a vector of  numbers in `R`, we use the function `c()` (for _concatenate_). Any numbers inside the parentheses are joined together.

In [1]:
x <- c(1, 2, 3, 4)
x

[1] 1 2 3 4

In [2]:
(x = c(2, 6, 5))
y = c(6, 2, 9)
y

[1] 2 6 5

[1] 6 2 9

The `length()` of a vector can be found

In [3]:
length(x)

[1] 3

The `ls()` function lists all of the objects saved so far. `rm()` will delete an object.

In [4]:
ls()

[1] "x" "y"

In [5]:
rm(y)
ls()

[1] "x"

You can also delete all objects at once.

In [8]:
x <- c(1, 2, 3)
y <- c(2, 4, 6)
z <- c(3, 6, 9)
ls()
rm(list = ls())
cat("---\n")
ls()

[1] "x" "y" "z"

---


character(0)

The `matrix()` function can be used to create a matrix of numbers. To learn more about the `matrix()` function you can use the `?` operator to print the help file.

In [9]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
          length 2 giving the row and column names respectively.  An
          empty list is treated as ‘NULL’, and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than ‘NULL’) ‘rownames’.  The default,
          ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
     infer it from the length of ‘data’ and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in ‘data’ to fill the matrix, then
     the elements in ‘data’ are recycled.  If ‘data’ has length zero,
     ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
     raw vectors) and ‘NULL’ for lists.

     ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
     attribute of length 2 and ‘FALSE’ otherwise.  Note that a
     ‘data.frame’ is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     ‘as.matrix’ is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying ‘as.vector’ to
     factors and ‘format’ to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     ‘is.matrix’ is a primitive function.

     The ‘print’ method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form ‘integer,7’ indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like

       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)
     
     will avoid duplicating ‘x’ _and_ preserve ‘class(x)’ which may be
     useful, e.g., for ‘Date’ objects.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘data.matrix’, which attempts to convert to a numeric matrix

To create a matrix

In [11]:
x <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

The default behavior of `matrix()` is to fill in columns first. You can change this behavior and have `matrix()` fill in rows first using the `byrow = TRUE` option.

In [12]:
matrix(c(1,2,3,4), 2, 2, byrow = TRUE)

[,1] [,2]
[1,] 1    2   
[2,] 3    4

The `sqrt()` function returns the square root of each element of the vector or matrix. Similarly the `^` operator will raise the element to a power.

In [13]:
sqrt(x)
x^2

[,1]     [,2]    
[1,] 1.000000 1.732051
[2,] 1.414214 2.000000

[,1] [,2]
[1,] 1     9  
[2,] 4    16

The `rnorm()` function generates a vector of random normal variables, with first argument `n` the sample size.

In [14]:
x <- rnorm(50)
y <- x + rnorm(50, mean = 50, sd = .1)
cor(x, y)

[1] 0.9957556

To reproduce random numbers. It is good to set a seed.

In [19]:
set.seed(1303)
rnorm(1)

[1] -1.143976

Otherwise you are not guaranteed to get the same results

In [20]:
rnorm(1)

[1] 1.342129

In [21]:
set.seed(1303)
rnorm(1)

[1] -1.143976